<?php
/**
* @file
* Simple module that provides a block that display user related links(login, register, reset password)
* @see http://www.xarala.sn
*/

/**
* Implementation of hook_block_info()
*/
function authlinks_block_info() {

  $blocks['authlinks'] = array(
    'info' => t('authlinks'), 
    'cache' => DRUPAL_NO_CACHE,
  );


  return $blocks;
}

/**
* Implementation of hook_block_view()
*/
function authlinks_block_view($delta = '') {

  $block = array();

  $block['subject'] = t('authlinks');
  $block['content'] = authlinks_get_links();

  return $block;
}

/**
 * Return links for auth
 */
function authlinks_get_links()
{

  /**
   * get a ref to the drupal current user
   *
   */
  global $user;

  $authlinks  = "<ul>";
  /**
   * user is not logged in
   */ 
  if (!$user->uid)
  {
    $authlinks .= "<li>". l(t('créer un compte'), 'user/register', array('attributes' => array('title' => t('créez un compte sur on-ven.')))). " |</li>";
    $authlinks .= "<li> ". l(t('connectez vous'), 'user/login', array('attributes' => array('title' => t('identifiez vous sur on-ven.')))). " |</li>";
    $authlinks .= "<li>". l(t(' mot de passe oublié?'), 'user/password', array('attributes' => array('title' => t('récuperez votre mot de passe par email.')))). "</li>";
  }
  /**
   * user is logged in
   */
  else
  { 
    
    $authlinks .= "<li>". l(t('Mon profil'), 'user/'. $user->uid, array('attributes' => array('title' => t('fermez votre session sur on-ven.')))). " | </li>";
    $authlinks .= "<li>". l(t('Se déconnecter'), 'user/logout', array('attributes' => array('title' => t('fermez votre session sur on-ven.')))). "</li>";
  }

  $authlinks .=  "</ul>";


  return $authlinks;  
  
}
